[LEVEL: ERROR TIME: 2017-07-26 03:27:32,469 MODULE: exception] 
Internal Server Error: /cart/add/1/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 28, in cart_add
    'cart': Cart(request).cart.values(),
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_values([{'id': '4', 'price': '1000', 'quantity': 2}, {'id': '1', 'price': '200', 'quantity': 13}, {'id': '3', 'price': '150', 'quantity': 1}]) is not JSON serializable
[LEVEL: ERROR TIME: 2017-07-26 03:28:18,608 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 28, in cart_add
    'cart': Cart(request).cart.values(),
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_values([{'id': '4', 'price': '1000', 'quantity': 2}, {'id': '1', 'price': '200', 'quantity': 12}, {'id': '3', 'price': '150', 'quantity': 1}]) is not JSON serializable
[LEVEL: ERROR TIME: 2017-07-26 03:28:33,098 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 28, in cart_add
    'cart': Cart(request).cart.values(),
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_values([{'id': '4', 'price': '1000', 'quantity': 2}, {'id': '1', 'price': '200', 'quantity': 12}, {'id': '3', 'price': '150', 'quantity': 1}]) is not JSON serializable
[LEVEL: ERROR TIME: 2017-07-26 03:28:41,165 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 28, in cart_add
    'cart': Cart(request).cart.values(),
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_values([{'id': '4', 'price': '1000', 'quantity': 2}, {'id': '1', 'price': '200', 'quantity': 12}, {'id': '3', 'price': '150', 'quantity': 2}]) is not JSON serializable
[LEVEL: ERROR TIME: 2017-07-26 03:30:16,988 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 28, in cart_add
    'cart': Cart(request).cart.values()
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_values([{'id': '1', 'quantity': 12, 'price': '200'}, {'id': '4', 'quantity': 2, 'price': '1000'}, {'id': '3', 'quantity': 2, 'price': '150'}]) is not JSON serializable
[LEVEL: ERROR TIME: 2017-07-26 03:32:17,832 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 28, in cart_add
    'cart': Cart(request).cart.values()
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_values([{'id': '4', 'quantity': 2, 'price': '1000'}, {'id': '3', 'quantity': 3, 'price': '150'}, {'id': '1', 'quantity': 12, 'price': '200'}]) is not JSON serializable
[LEVEL: WARNING TIME: 2017-07-26 03:32:42,886 MODULE: http] 
Method Not Allowed (GET): /cart/add/3/
[LEVEL: ERROR TIME: 2017-07-26 03:32:48,251 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 28, in cart_add
    'cart': Cart(request).values()
AttributeError: 'Cart' object has no attribute 'values'
[LEVEL: ERROR TIME: 2017-07-26 03:33:06,717 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 28, in cart_add
    'cart': Cart(request).cart.items()
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_items([('1', {'price': '200', 'quantity': 12, 'id': '1'}), ('3', {'price': '150', 'id': '3', 'quantity': 3}), ('4', {'price': '1000', 'quantity': 2, 'id': '4'})]) is not JSON serializable
[LEVEL: ERROR TIME: 2017-07-26 03:38:25,467 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 30, in cart_add
    return HttpResponse(json.dumps(({'cart': Cart(request).cart.values(), 'total_price': str(Cart(request).get_total_price())})))
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_values([{'id': '1', 'price': '200', 'quantity': 12}, {'id': '3', 'price': '150', 'quantity': 3}, {'id': '4', 'price': '1000', 'quantity': 2}]) is not JSON serializable
[LEVEL: WARNING TIME: 2017-07-26 03:38:47,072 MODULE: http] 
Method Not Allowed (GET): /cart/add/3/
[LEVEL: WARNING TIME: 2017-07-26 03:38:48,954 MODULE: http] 
Method Not Allowed (GET): /cart/add/3/
[LEVEL: ERROR TIME: 2017-07-26 03:47:54,822 MODULE: exception] 
Internal Server Error: /cart/add/4/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 18, in cart_add
    print(form.cleaned_data)
AttributeError: 'CartAddProductForm' object has no attribute 'cleaned_data'
[LEVEL: ERROR TIME: 2017-07-26 03:48:11,838 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 18, in cart_add
    print(form.cleaned_data)
AttributeError: 'CartAddProductForm' object has no attribute 'cleaned_data'
[LEVEL: ERROR TIME: 2017-07-26 03:48:15,615 MODULE: exception] 
Internal Server Error: /cart/add/4/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 18, in cart_add
    print(form.cleaned_data)
AttributeError: 'CartAddProductForm' object has no attribute 'cleaned_data'
[LEVEL: ERROR TIME: 2017-07-26 03:48:19,883 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 18, in cart_add
    print(form.cleaned_data)
AttributeError: 'CartAddProductForm' object has no attribute 'cleaned_data'
[LEVEL: ERROR TIME: 2017-07-26 03:48:32,756 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 18, in cart_add
    print(form.cleaned_data)
AttributeError: 'CartAddProductForm' object has no attribute 'cleaned_data'
[LEVEL: ERROR TIME: 2017-07-26 03:48:35,901 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 18, in cart_add
    print(form.cleaned_data)
AttributeError: 'CartAddProductForm' object has no attribute 'cleaned_data'
[LEVEL: ERROR TIME: 2017-07-26 03:48:40,810 MODULE: exception] 
Internal Server Error: /cart/add/3/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/cart/views.py", line 18, in cart_add
    print(form.cleaned_data)
AttributeError: 'CartAddProductForm' object has no attribute 'cleaned_data'
[LEVEL: ERROR TIME: 2017-07-26 04:06:01,531 MODULE: exception] 
Internal Server Error: /order/create/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/orders/views.py", line 21, in order_create_view
    'form': form})
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: orders/create.html.html
[LEVEL: WARNING TIME: 2017-07-26 04:06:02,409 MODULE: base] 
Not Found: /favicon.ico/
[LEVEL: ERROR TIME: 2017-07-26 04:06:02,912 MODULE: exception] 
Internal Server Error: /order/create/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/orders/views.py", line 21, in order_create_view
    'form': form})
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: orders/create.html.html
[LEVEL: WARNING TIME: 2017-07-26 04:48:23,202 MODULE: base] 
Not Found: /favicon.ico/
[LEVEL: WARNING TIME: 2017-07-26 05:01:05,628 MODULE: base] 
Not Found: /favicon.ico/
[LEVEL: WARNING TIME: 2017-07-26 05:26:30,286 MODULE: base] 
Not Found: /feedback/1/
[LEVEL: WARNING TIME: 2017-07-26 05:28:28,467 MODULE: base] 
Not Found: /feedback/1/
[LEVEL: WARNING TIME: 2017-07-26 05:29:29,784 MODULE: base] 
Not Found: /feedback/1/
[LEVEL: WARNING TIME: 2017-07-26 05:29:44,008 MODULE: base] 
Not Found: /feedback/
[LEVEL: WARNING TIME: 2017-07-26 05:29:47,370 MODULE: base] 
Not Found: /feedback/1/
[LEVEL: WARNING TIME: 2017-07-26 05:30:04,646 MODULE: base] 
Not Found: /feedback/1/
[LEVEL: WARNING TIME: 2017-07-26 05:30:23,416 MODULE: base] 
Not Found: /feedback/1/
[LEVEL: WARNING TIME: 2017-07-26 05:30:40,494 MODULE: base] 
Not Found: /feedback/1/
[LEVEL: WARNING TIME: 2017-07-26 05:30:45,729 MODULE: base] 
Not Found: /feedback/
[LEVEL: ERROR TIME: 2017-07-26 05:36:52,204 MODULE: exception] 
Internal Server Error: /feedback/1/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/dynamic_form/views.py", line 13, in custom_form
    form = CustomForm(request.POST, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/dynamic_form/forms.py", line 10, in __init__
    form = kwargs.pop('extra')
KeyError: 'extra'
[LEVEL: ERROR TIME: 2017-07-26 05:37:24,029 MODULE: exception] 
Internal Server Error: /feedback/1/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/dynamic_form/views.py", line 12, in custom_form
    form = CustomForm(request.POST, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/dynamic_form/forms.py", line 10, in __init__
    form = kwargs.pop('extra')
KeyError: 'extra'
[LEVEL: WARNING TIME: 2017-07-26 05:38:40,215 MODULE: base] 
Not Found: /favicon.ico/
[LEVEL: WARNING TIME: 2017-07-26 11:57:05,197 MODULE: base] 
Method Not Allowed (POST): /order/create/order
[LEVEL: ERROR TIME: 2017-07-26 12:01:52,190 MODULE: exception] 
Internal Server Error: /order/create/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: ОШИБКА:  нулевое значение в столбце "gender" нарушает ограничение NOT NULL
DETAIL:  Ошибочная строка содержит (1, qwe, qwe@qwe.ru, 2017-07-26 12:01:52.018887+00, 2017-07-26 12:01:52.018912+00, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/orders/views.py", line 30, in order_create
    order = form.save()
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/forms/models.py", line 463, in save
    self.instance.save()
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: ОШИБКА:  нулевое значение в столбце "gender" нарушает ограничение NOT NULL
DETAIL:  Ошибочная строка содержит (1, qwe, qwe@qwe.ru, 2017-07-26 12:01:52.018887+00, 2017-07-26 12:01:52.018912+00, null).

[LEVEL: ERROR TIME: 2017-07-26 12:07:53,499 MODULE: exception] 
Internal Server Error: /order/view/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/source/app/orders/views.py", line 19, in order_create_view
    form = OrderCreateForm()
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/forms/models.py", line 290, in __init__
    raise ValueError('ModelForm has no model class specified.')
ValueError: ModelForm has no model class specified.
[LEVEL: WARNING TIME: 2017-07-26 12:16:07,112 MODULE: base] 
Not Found: /favicon.ico/
[LEVEL: WARNING TIME: 2017-07-26 13:01:22,717 MODULE: base] 
Not Found: /favicon.ico/
[LEVEL: WARNING TIME: 2017-07-26 13:13:27,717 MODULE: exception] 
Forbidden (Permission denied): /admin/orders/order/6/change/
[LEVEL: WARNING TIME: 2017-07-26 13:13:29,718 MODULE: exception] 
Forbidden (Permission denied): /admin/orders/order/6/change/
[LEVEL: WARNING TIME: 2017-07-26 13:14:24,412 MODULE: exception] 
Forbidden (Permission denied): /admin/orders/order/6/change/
[LEVEL: WARNING TIME: 2017-07-26 13:14:25,239 MODULE: exception] 
Forbidden (Permission denied): /admin/orders/order/6/change/
[LEVEL: WARNING TIME: 2017-07-26 13:15:17,176 MODULE: base] 
Not Found: /favicon.ico/
[LEVEL: ERROR TIME: 2017-07-26 13:25:11,253 MODULE: exception] 
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: admin:admin/index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/backends/django.py", line 68, in render
    reraise(exc, self.backend)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/backends/django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: admin:admin/index.html
[LEVEL: ERROR TIME: 2017-07-26 13:25:23,016 MODULE: exception] 
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: admin:admin/index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/backends/django.py", line 68, in render
    reraise(exc, self.backend)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/backends/django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: admin:admin/index.html
[LEVEL: ERROR TIME: 2017-07-26 13:27:07,978 MODULE: exception] 
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: ОШИБКА:  отношение "admin_tools_menu_bookmark" не существует
LINE 1: ..."."url", "admin_tools_menu_bookmark"."title" FROM "admin_too...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/library.py", line 245, in render
    return t.render(new_context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/library.py", line 225, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/admin_tools/menu/templatetags/admin_tools_menu_tags.py", line 67, in admin_tools_render_menu_item
    item.init_with_context(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/admin_tools/menu/items.py", line 348, in init_with_context
    for b in Bookmark.objects.filter(user=context['request'].user):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 886, in execute_sql
    raise original_exception
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ОШИБКА:  отношение "admin_tools_menu_bookmark" не существует
LINE 1: ..."."url", "admin_tools_menu_bookmark"."title" FROM "admin_too...
                                                             ^

[LEVEL: ERROR TIME: 2017-07-26 13:27:22,546 MODULE: exception] 
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/library.py", line 245, in render
    return t.render(new_context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'admin-tools-dashboard-set-preferences' not found. 'admin-tools-dashboard-set-preferences' is not a valid view function or pattern name.
[LEVEL: ERROR TIME: 2017-07-26 13:27:38,413 MODULE: exception] 
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/library.py", line 245, in render
    return t.render(new_context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'admin-tools-dashboard-set-preferences' not found. 'admin-tools-dashboard-set-preferences' is not a valid view function or pattern name.
[LEVEL: ERROR TIME: 2017-07-26 13:28:16,441 MODULE: exception] 
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/library.py", line 245, in render
    return t.render(new_context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/template/defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/druhound/Develop/sites/snowderevnya/venv-snow/lib/python3.5/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'admin-tools-dashboard-set-preferences' not found. 'admin-tools-dashboard-set-preferences' is not a valid view function or pattern name.
